# Configuration file ESPCN 

training:

  training file: 'data/datasets/91-image_x3.h5'
  eval file: 'data/datasets/Set5_x3.h5'
  output dir: 'data/weights'

  scale: 3
  lr: 1e-3
  batch size: 16
  number of epochs: 200
  number of workers: 8
  seed: 123

test image:
  weights file: 'data/weights/x3/best.pth'
  scale: 3
  image dir: 'data/images'
  # name inside images dir : file mode - process one file
  image file: 'baboon.bmp'
  
test video:
  weights file: 'data/weights/x3/best.pth'
  scale: 3
  video dir: 'data/videos'
  #name inside video dir : file mode - process one file  
  video file: 'vid1.mp4'
  