# Configuration file for ESPCN-PyTorch

# Nested dictionary contains configuration values for all modes. 
# When using a mode, edit configuration values according to your data/ directory
# Modes:
#     training: trains the network
#     test image: process image(s); Batch mode for entire directories.
#     test video: process video(s); Batch mode for entire directories.
#     visualize filters: plots filter visualizations for each convolutional layer and saves them


training:

  training file: 'data/datasets/91-image_x3.h5'
  eval file: 'data/datasets/Set5_x3.h5'
  output dir: 'data/weights'

  scale: 3
  lr: 1e-3
  batch size: 16
  number of epochs: 200
  number of workers: 8
  seed: 123

test image:
  weights file: 'data/weights/x3/best.pth'
  scale: 3
  image dir: 'data/images'
  # if using batch mode (-b, --batch), then image file is ignored
  image file: 'baboon.bmp'
  
test video:
  weights file: 'data/weights/x3/best.pth'
  scale: 3
  video dir: 'data/xiph-videos'
  # if using batch mode (-b, --batch), then image file is ignored
  video file: 'bus_cif.avi'

visualize filters:
  weights file: 'data/weights/x3/best.pth'
  scale: 3